# Generated by Django 3.0.5 on 2020-04-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_auto_20200423_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
