# Generated by Django 3.0.5 on 2020-04-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_auto_20200423_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
